name: pokerapp
description: A new Flutter application.

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  emoji_picker:
    path: ./emoji_picker
  audio_recorder:
    git:
      url: https://github.com/New-Voyager/audio_recorder.git
      ref: master
  dart_nats:
    git:
      url: https://github.com/New-Voyager/dart-nats.git
      ref: master
  tenor:
    git:
      url: https://github.com/New-Voyager/tenor.git
      ref: master
  after_layout: ^1.1.0
  animated_text_kit: ^4.1.1
  audioplayers: 0.17.0
  badges: ^2.0.1
  blinking_text: ^1.0.1+2
  cached_network_image: 2.3.2+1
  charts_flutter: ^0.10.0
  cryptography: ^2.0.1
  cupertino_icons: ^0.1.3
  curved_bottom_navigation: ^1.0.0
  device_info: ^2.0.2
  equatable: ^1.2.5
  firebase_analytics: ^8.0.2
  firebase_core: ^1.1.0
  firebase_messaging: ^10.0.0
  flip_card: ^0.4.4
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.2
  flutter_circular_slider: ^2.5.0
  flutter_gifimage: ^1.0.1
  flutter_keyboard_visibility: ^3.2.2
  flutter_speed_dial: ^3.0.5
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.21.0+1
  flutter_switch: ^0.3.1
  flutter_udid: ^1.0.1
  flutter_webrtc: ^0.6.3
  font_awesome_flutter: ^8.8.1
  get_it: ^6.1.1
  graphql_flutter: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.12.2
  in_app_purchase: ^0.5.2
  intl: ^0.16.1
  just_audio: ^0.6.12
  lottie: ^0.7.0
  modal_progress_hud: ^0.1.3
  overlay_support: ^1.2.1
  path_provider: ^1.6.24
  permission_handler: ^5.0.1
  provider: ^4.3.1
  share: ^2.0.1
  shared_preferences: ^0.5.10
  sizer: ^1.1.8
  sleek_circular_slider: ^2.0.0
  sliding_up_panel: ^1.0.2
  stream_channel: ^2.1.0
  timer_count_down: ^1.0.4+1
  tuple: ^1.0.3
  wakelock: ^0.5.2
  web_socket_channel: ^2.0.0
  zflutter: ^0.0.1+2

dependency_overrides:
  http: ^0.12.2
  http_parser: ^4.0.0
  plugin_platform_interface: ^1.0.1
  json_annotation: ^4.0.1
  uuid: ^3.0.4
  path_provider: ^1.6.24
  crypto: ^3.0.0
  mime: ^1.0.0
  logging: ^1.0.1
  file: ^6.1.1
  convert: ^3.0.0
  args: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/attributions/
    - assets/animations/
    - assets/images/backgrounds/
    - assets/images/table/
    - assets/images/game/
    - assets/images/chips/
    - assets/images/speak/
    - assets/images/network_connectivity/
    - assets/images/betchips/
    - assets/images/card_back/set1/
    - assets/images/card_back/set2/
    - assets/sound_effects/
    - assets/images/gamesettings/
    - assets/images/game-settings/
    - assets/images/name_plates/
    - assets/sample-data/
    - assets/sample-data/handlog/
    - assets/sample-data/handlog/holdem/
    - assets/sample-data/handlog/plo/
    - assets/sample-data/handlog/plo-hilo/
    - assets/sample-data/handlog/5card-plo/
    - assets/sample-data/completed-game.json
    - assets/sample-data/completed-game2.json
    - assets/sample-data/handlog.json
    - assets/sample-data/weekly-data.json
    - assets/animations/
    - assets/images/cards/
    - assets/images/club/
    - assets/images/livegames/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: NoticiaText
      fonts:
        - asset: assets/fonts/NoticiaText-Bold.ttf
          weight: 700
    - family: Rockwell
      fonts:
        - asset: assets/fonts/Rockwell-Regular.ttf
        - asset: assets/fonts/Rockwell-Bold.ttf
          weight: 700
    - family: SourceSerif
      fonts:
        - asset: assets/fonts/SourceSerifPro-SemiBold.ttf
          weight: 400
    - family: Trocchi
      fonts:
        - asset: assets/fonts/Trocchi-Regular.ttf
          weight: 400
    - family: Domine
      fonts:
        - asset: assets/fonts/Domine-VariableFont_wght.ttf
          weight: 700
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata-Bold.ttf
          weight: 700

    # icon packs
    - family: AppIcons
      fonts:
        - asset: assets/icons/app_icons.ttf

    # club screen icons
    - family: ClubScreenIcons
      fonts:
        - asset: assets/icons/club_screen_icons.ttf
