---
name: pokerapp
description: PokerClubApp
publish_to: "none"
version: 0.7.12+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  after_layout: ^1.1.0
  animated_text_kit: ^4.2.1
  animated_widgets: ^1.1.0
  archive: ^3.1.2
  audioplayers: ^0.20.1
  badges: ^2.0.1
  blinking_text: ^1.0.1+2
  bouncing_widget: ^2.0.0
  buttons_tabbar: ^1.3.2
  cached_network_image: ^3.1.0
  charts_flutter: ^0.11.0
  connectivity: ^3.0.6
  connectivity_for_web: ^0.4.0+1
  cryptography: ^2.0.2
  csv: ^5.0.1
  cupertino_icons: ^1.0.3
  data_connection_checker: ^0.3.4
  data_table_2: ^2.2.0
  device_info: ^2.0.2
  dropdown_button2: ^1.1.1
  equatable: ^2.0.3
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  flip_card: ^0.5.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_chat_bubble: ^2.0.0
  flutter_date_pickers: ^0.2.6
  flutter_fgbg: ^0.1.0
  flutter_html: ^2.1.5
  flutter_local_notifications: ^8.2.0
  flutter_speed_dial: 4.3.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  flutter_udid: ^2.0.0
  flutter_webrtc: ^0.8.1
  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  graphql_flutter: ^5.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  horizontal_data_table: ^3.5.0
  http: ^0.13.3
  image_picker: ^0.8.4+1
  in_app_purchase: 1.0.8
  intl: ^0.17.0
  ios_utsname_ext: ^2.1.0
  jiffy: ^4.1.0
  just_audio: ^0.9.18
  livekit_client: ^0.5.6
  location: ^4.2.0
  lottie: ^1.1.0
  onboarding_overlay: ^2.3.5
  overlay_support: ^1.2.1
  path_provider: ^2.0.4
  permission_handler: 6.0.1
  plugin_platform_interface: ^2.0.1
  protobuf: ^2.0.0
  provider: ^6.0.0
  record: ^3.0.0
  responsive_sizer: ^3.0.4+4
  share: ^2.0.4
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  simple_tooltip: ^1.0.0
  sizer: ^2.0.0
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  stream_channel: ^2.1.0
  timeago: ^3.1.0
  timer_count_down: ^2.2.0
  tuple: ^2.0.0
  upgrader: ^3.5.1
  url_launcher: ^6.0.17
  uuid: ^3.0.4
  vibration: ^1.7.3
  wakelock: ^0.5.6
  web_socket_channel: ^2.1.0
  bordered_text: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: 2.0.2
  flutter_xlider: 3.4.0

dev_dependencies:
  build_test: ^2.1.3
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
dependency_overrides:
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/images/attributions/
  - assets/animations/
  - assets/images/backgrounds/
  - assets/images/table/
  - assets/images/game/
  - assets/images/game-screen/
  - assets/images/speak/
  - assets/images/network_connectivity/
  - assets/images/betchips/
  - assets/images/card_back/set1/
  - assets/images/card_back/set2/
  - assets/sound_effects/
  - assets/images/gamesettings/
  - assets/images/game-settings/
  - assets/images/name_plates/
  - assets/images/default/cardface/
  - assets/images/default/
  - assets/sample-data/
  - assets/sample-data/handlog/
  - assets/sample-data/handlog/holdem/
  - assets/sample-data/handlog/plo/
  - assets/sample-data/handlog/plo-hilo/
  - assets/sample-data/handlog/5card-plo/
  - assets/sample-data/completed-game.json
  - assets/sample-data/completed-game2.json
  - assets/sample-data/handlog.json
  - assets/sample-data/weekly-data.json
  - assets/animations/
  - assets/images/cards/
  - assets/images/club/
  - assets/images/livegames/
  - assets/images/color-card_face/
  - assets/images/card_face/
  - assets/language/
  - assets/json/nameplates.json
  - assets/json/mockdata.json
  fonts:
  - family: Lato
    fonts:
    - asset: assets/fonts/Lato-Regular.ttf
    - asset: assets/fonts/Lato-Thin.ttf
      weight: 100
    - asset: assets/fonts/Lato-Light.ttf
      weight: 300
    - asset: assets/fonts/Lato-Bold.ttf
      weight: 700
    - asset: assets/fonts/Lato-Black.ttf
      weight: 900
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Regular.ttf
    - asset: assets/fonts/Poppins-Light.ttf
      weight: 300
    - asset: assets/fonts/Poppins-Bold.ttf
      weight: 700
  - family: NoticiaText
    fonts:
    - asset: assets/fonts/NoticiaText-Bold.ttf
      weight: 700
  - family: Rockwell
    fonts:
    - asset: assets/fonts/Rockwell-Regular.ttf
    - asset: assets/fonts/Rockwell-Bold.ttf
      weight: 700
  - family: SourceSerif
    fonts:
    - asset: assets/fonts/SourceSerifPro-SemiBold.ttf
      weight: 400
  - family: Trocchi
    fonts:
    - asset: assets/fonts/Trocchi-Regular.ttf
      weight: 400
  - family: Domine
    fonts:
    - asset: assets/fonts/Domine-VariableFont_wght.ttf
      weight: 700
  - family: Literata
    fonts:
    - asset: assets/fonts/Literata-Bold.ttf
      weight: 700
  - family: AppIcons
    fonts:
    - asset: assets/icons/app_icons.ttf
  - family: ClubScreenIcons
    fonts:
    - asset: assets/icons/club_screen_icons.ttf
flutter_native_splash:
  background_image: assets/images/splash.png
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/logo.png
