name: pokerapp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0

  modal_progress_hud: ^0.1.3

  # state management
  provider: ^4.3.1

  # icon pack
  font_awesome_flutter: ^8.8.1

  # networking
  graphql_flutter: ^3.1.0
  http: ^0.12.2
  dart_nats:
    git:
      url: https://github.com/jyotirmoy-paul/dart-nats.git
      ref: master

  # device id
  flutter_udid: ^1.0.1

  # storage
  shared_preferences: ^0.5.10

  # network images
  cached_network_image: 2.3.2+1

  # formatter
  intl: ^0.16.1

  # timer
  timer_count_down: ^1.0.4+1

  # audio playing
  audioplayers: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/images/card_back/set1/
   - assets/images/card_back/set2/
   - assets/sound_effects/

  fonts:
   - family: Lato
     fonts:
       - asset: assets/fonts/Lato-Regular.ttf
       - asset: assets/fonts/Lato-Thin.ttf
         weight: 100
       - asset: assets/fonts/Lato-Light.ttf
         weight: 300
       - asset: assets/fonts/Lato-Bold.ttf
         weight: 700
       - asset: assets/fonts/Lato-Black.ttf
         weight: 900
   - family: NoticiaText
     fonts:
       - asset: assets/fonts/NoticiaText-Bold.ttf
         weight: 700

    # icon packs
   - family: AppIcons
     fonts:
       - asset: assets/icons/app_icons.ttf