/// Flutter icons ClubScreenIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ClubScreenIcons
///      fonts:
///       - asset: fonts/ClubScreenIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ClubScreenIcons {
  ClubScreenIcons._();

  static const _kFontFam = 'ClubScreenIcons';
  static const _kFontPkg = null;

  static const IconData announcements =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin_stack =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData membership =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData reward =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
