version: '3'

services:
  game-server:
    image: ${GAME_SERVER_IMAGE}
    tty: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - nats
      - api-server
    environment:
      PERSIST_METHOD: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      API_SERVER_INTERNAL_URL: http://api-server:9502
      NATS_URL: nats://nats:4222
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: 'game'
      POSTGRES_DB: 'game'
      DEBUG_CONNECTIVITY_CHECK: 0
      ENABLE_ENCRYPTION: 1
      LOG_LEVEL: debug
    volumes:
      - '${PROJECT_ROOT}/dev/gameserver:/app/mounted'
    command:
      - "/bin/sh"
      - "-c"
      - "/app/game-server --server"

  nats:
    image: ${NATS_SERVER_IMAGE}
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
      - 9222:9222
    command:
      - "/bin/sh"
      - "-c"
      - "nats-server --config /etc/nats/nats-server.conf ${NATS_OPTS}"

  redis:
    image: ${REDIS_IMAGE}
    restart: always
    ports:
      - 6379:6379

  api-server:
    image: ${API_SERVER_IMAGE}
    restart: always
    ports:
      - 9501:9501
    depends_on:
      - postgres
      - nats
    command:
      - "/bin/sh"
      - "-c"
      - "sleep 5 && yarn run-docker"
    environment:
      EXTERNAL_ENDPOINTS: 1
      INTERNAL_ENDPOINTS: 1
      NATS_URL: nats://nats:4222
      BOTRUNNER_URL: http://botrunner:8081
      TIMER_URL: http://timer:8082
      SCHEDULER_URL: http://scheduler:8083
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: 'game'
      POSTGRES_DB: 'game'

  postgres:
    image: ${POSTGRES_IMAGE}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: 'game'

  botrunner:
    image: ${BOTRUNNER_IMAGE}
    tty: true
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - api-server
    environment:
      API_SERVER_URL: http://api-server:9501
      API_SERVER_INTERNAL_URL: http://api-server:9502
      NATS_URL: nats://nats:4222
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: game
      POSTGRES_PASSWORD: game
      POSTGRES_DB: game
      ENABLE_ENCRYPTION: 1
      LOG_LEVEL: debug
    volumes:
      - ../botrunner_scripts:/app/botrunner_scripts

  timer:
    image: ${TIMER_IMAGE}
    tty: true
    restart: always
    ports:
      - 8082:8082
    environment:
      API_SERVER_INTERNAL_URL: http://api-server:9502
      LOG_LEVEL: debug

  scheduler:
    image: ${SCHEDULER_IMAGE}
    tty: true
    restart: always
    ports:
      - 8083:8083
    environment:
      API_SERVER_INTERNAL_URL: http://api-server:9502
      LOG_LEVEL: info
      POST_PROCESSING_TIMEOUT_SEC: 120
      EXPIRE_GAMES_INTERVAL_SEC: 30
      EXPIRE_GAMES_TIMEOUT_SEC: 30

volumes:
  db-data:
      
networks:
  default:
    external:
      name: game
