name: emoji_picker
description: Flutter package for emoji
version: 1.0.0
homepage: null

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jeffg.emoji_picker
        pluginClass: EmojiPickerPlugin
      ios:
        pluginClass: EmojiPickerPlugin
